### ISSUE TITLE
Background broken. YouTube logo broken.

### ISSUE THREAD

**Issue by r4ymond2** [sakuramochi0/prichan-stylesheet#1]
The background and YouTube logo is currently broken

**Comment by sakuramochi0** [comment]
@r4ymond2 Thank you for reporting a bug! I've noticed the background broken but didn't notice logo problem. Thanks for letting me know that. 

I have little time to fix them recently. But I'd like to fix them if I have a time. The fix will be pushed to userstyle.org page. Stay tuned!

**Comment by sakuramochi0** [comment]
I could not see that YouTube logo is broken on my environment.

- Browser: Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)

Can you provide your environment information (OS, Browser, etc.)? Make sure you don't use extensions which blocks some content.

**Comment by sakuramochi0** [comment]
@r4ymond2 I could not see that YouTube logo is broken on my following environments:

1. 
- Browser: Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)
- Extension: Stylus v1.5.11

2.
- Browser: Mozilla Firefox v78.0.2 (64-bit)
- Extension: Stylus v1.5.11

Can you provide your environment information (OS, Browser, Extension etc.)? Make sure you don't use extensions which blocks some content.

**Comment by jdramirez165** [comment]
The logo is still the same so its fine on my side. The background is just white instead of the one seen in the show.

**Comment by r4ymond2** [comment]
> @r4ymond2 I could not see that YouTube logo is broken on my following environments:
> 
> 
> * Browser: Google Chrome Version 84.0.4147.89 (Official Build) (64-bit)
> * Extension: Stylus v1.5.11
> 
> 
> * Browser: Mozilla Firefox v78.0.2 (64-bit)
> * Extension: Stylus v1.5.11
> 
> Can you provide your environment information (OS, Browser, Extension etc.)? Make sure you don't use extensions which blocks some content.

I am using Windows 7 with the new Edge browser
The extension is Stylus v1.15.11
![image](https://user-images.githubusercontent.com/10260478/88981075-2621db80-d293-11ea-8e4c-f0afd1118d08.png)

**Comment by sakuramochi0** [comment]
@r4ymond2 @jdramirez165 Thank you so much for providing information! About background issue, I found the way to fix this problem. I will publish the update in several days!

@r4ymond2, I see you are using uBlock extension and it blocks 33 contents. So these may block the logo image. What happens if making these extensions disabled?

Currently, these files are loaded from external site and maybe I can move image to other place to avoid loading problem. This is another option.

**Comment by r4ymond2** [comment]
> @r4ymond2 @jdramirez165 Thank you so much for providing information! About background issue, I found the way to fix this problem. I will publish the update in several days!
> 
> @r4ymond2, I see you are using uBlock extension and it blocks 33 contents. So these may block the logo image. What happens if making these extensions disabled?
> 
> Currently, these files are loaded from external site and maybe I can move image to other place to avoid loading problem. This is another option.

Disabled uBlock and still won't show
![image](https://user-images.githubusercontent.com/10260478/89092441-dbca5880-d37f-11ea-80e2-add6592870c1.png)

**Comment by sakuramochi0** [comment]
@r4ymond2 @jdramirez165 Hello, I've just the new release (v2.0.4) to fix some problems: https://userstyles.org/styles/167470/kiratto-prichan. Cloud you check if applying this update fixes the problems?

**Comment by r4ymond2** [comment]
> @r4ymond2 @jdramirez165 Hello, I've just the new release (v2.0.4) to fix some problems: https://userstyles.org/styles/167470/kiratto-prichan. Cloud you check if applying this update fixes the problems?

fixed for me now

**Comment by sakuramochi0** [comment]
@r4ymond2 Including the logo problem? I'm glad to hear that!🙂

**Comment by sakuramochi0** [comment]
I'm closing this issue. Feel free to reopen if the problem remains.

**Comment by r4ymond2** [comment]
It broke again

**Comment by r4ymond2** [comment]
Ok so I made a few edits to the code, I moved the urls from twimg to imgur and got it working again.
Here is an example of it working and the updated code.
![image](https://user-images.githubusercontent.com/10260478/90341513-2da0ee80-dfce-11ea-8ac6-d6f5ad6b6382.png)
[code.txt](https://github.com/sakuramochi0/prichan-stylesheet/files/5081217/code.txt)
