### ISSUE TITLE
Youtube logo over the PriChan logo.

### ISSUE THREAD

**Issue by jdramirez165** [sakuramochi0/prichan-stylesheet#3]
![image](https://user-images.githubusercontent.com/17467854/105378938-48dfec00-5c47-11eb-92a8-d79f57be89d1.png)
Please fix.

**Comment by sakuramochi0** [comment]
@jdramirez165 Thanks for reporting!

I recently updated the style to v2.0.5 on 2021-01-17. Did you update the style to this version? Please check here and try to update it: https://userstyles.org/styles/167470/kiratto-prichan

**Comment by jdramirez165** [comment]
Still has the Youtube logo.

**Comment by sakuramochi0** [comment]
Sorry for the late check. This issue should have been fixed now. Please try the latest v2.0.6: https://userstyles.org/styles/167470/kiratto-prichan.

**Comment by sakuramochi0** [comment]
Feel free to reopen the issue if the probrem remains!
