### ISSUE TITLE
White bar under top bar improper colour

### ISSUE THREAD

**Issue by NathanDreamweaver** [sakuramochi0/prichan-stylesheet#5]
![image](https://user-images.githubusercontent.com/15868262/123559364-dcd85580-d79b-11eb-9baf-68352530623f.png)
![image](https://user-images.githubusercontent.com/15868262/123559372-f2e61600-d79b-11eb-942e-f9e1775dc9e6.png)

**Comment by sakuramochi0** [comment]
Sorry for the late reply! This issue should have been fixed now.

<img width="1305" alt="Screen Shot 2022-08-12 at 8 10 30" src="https://user-images.githubusercontent.com/6568716/184257341-edf142ac-66cd-4b97-af7e-bc9dba2e6760.png">
